import { Column, DataValidation } from 'exceljs';
import { ICustomizeCell, IHeader, ListStyle } from '../interfaces/excel.interface';

export const importDebtCompartionHeader: IHeader[] = [
    {
        header: 'Stt',
        key: 'id',
        width: 7,
        formula: 'IF(OR(B{i}<>"",C{i}<>"",D{i}<>"",E{i}<>""),ROW()-ROW($A$1),"")',
        style: ListStyle.WHITE as Partial<Column>,
        children: [],
    },
    {
        header: 'Ngày',
        key: 'date',
        width: 20,
        dataValidation: {} as DataValidation,
        style: ListStyle.WHITE as Partial<Column>,
        children: [],
    },
    {
        header: 'Số HĐ VAT',
        key: 'vat',
        width: 10,
        dataValidation: {} as DataValidation,
        style: ListStyle.WHITE as Partial<Column>,
        children: [],
    },
    {
        header: 'Nội dung',
        key: 'content',
        width: 40,
        dataValidation: {} as DataValidation,
        style: ListStyle.WHITE as Partial<Column>,
        children: [],
    },
    {
        header: 'Thành tiền',
        key: 'intoMoney',
        width: 20,
        dataValidation: {} as DataValidation,
        style: ListStyle.WHITE as Partial<Column>,
        children: [
            {
                header: 'Vnđ',
                key: 'intoMoney',
                width: 20,
                style: ListStyle.YELLOW as Partial<Column>,
                children: [],
            },
        ],
    },
    {
        header: 'Thanh toán',
        key: 'payment',
        width: 60,
        dataValidation: {} as DataValidation,
        style: ListStyle.WHITE as Partial<Column>,
        children: [
            {
                header: 'Số tiền',
                key: 'money',
                width: 20,
                style: ListStyle.YELLOW as Partial<Column>,
                children: [],
            },
            {
                header: 'Ngày',
                key: 'paymentDate',
                width: 20,
                style: ListStyle.YELLOW as Partial<Column>,
                children: [],
            },
            {
                header: 'Ngân hàng',
                key: 'bank',
                width: 20,
                style: ListStyle.YELLOW as Partial<Column>,
                children: [],
            },
        ],
    },
    {
        header: 'Còn nợ',
        key: 'debt',
        width: 30,
        dataValidation: {} as DataValidation,
        style: ListStyle.WHITE as Partial<Column>,
        children: [
            {
                header: 'Vnđ',
                key: 'debt',
                width: 30,
                style: ListStyle.YELLOW as Partial<Column>,
                children: [],
            },
        ],
    },
    {
        header: 'Số ĐH',
        key: 'orderNumber',
        width: 30,
        dataValidation: {} as DataValidation,
        style: ListStyle.WHITE as Partial<Column>,
    },
    {
        header: 'Hạn thanh toán',
        key: 'paymentTerm',
        width: 30,
        dataValidation: {} as DataValidation,
        style: ListStyle.WHITE as Partial<Column>,
    },
    {
        header: 'Tạo đề nghị thanh toán',
        key: 'payRequest',
        width: 30,
        style: ListStyle.WHITE as Partial<Column>,
    },
    {
        header: 'Hoa hồng cho người bán',
        key: 'commission',
        width: 30,
        dataValidation: {} as DataValidation,
        style: ListStyle.GREEN as Partial<Column>,
    },
    {
        header: 'Thành tiền',
        key: 'commissionMoney',
        width: 30,
        dataValidation: {} as DataValidation,
        style: ListStyle.GREEN as Partial<Column>,
    },
    {
        header: 'Thanh toán',
        key: 'pay',
        width: 60,
        dataValidation: {} as DataValidation,
        style: ListStyle.GREEN as Partial<Column>,
        children: [
            {
                header: 'Số tiền',
                key: 'commissionPay',
                width: 20,
                style: ListStyle.GREEN as Partial<Column>,
            },
            {
                header: 'Ngày',
                key: 'commissionDate',
                width: 20,
                style: ListStyle.GREEN as Partial<Column>,
            },
            {
                header: 'Ngân hàng',
                key: 'commissionBank',
                width: 20,
                style: ListStyle.GREEN as Partial<Column>,
            },
        ],
    },
    {
        header: 'Còn nợ',
        key: 'commissionDebt',
        width: 30,
        dataValidation: {} as DataValidation,
        style: ListStyle.GREEN as Partial<Column>,
        children: [
            {
                header: 'Vnđ',
                key: 'commissionDebt',
                width: 30,
                style: ListStyle.GREEN as Partial<Column>,
            },
        ],
    },
    {
        header: 'Thông tin khách hàng',
        key: 'customer',
        width: 40,
        dataValidation: {} as DataValidation,
        style: ListStyle.GREEN as Partial<Column>,
        children: [
            {
                header: 'Số điện thoại',
                key: 'phone',
                width: 20,
                style: ListStyle.GREEN as Partial<Column>,
            },
            {
                header: 'Tên',
                key: 'name',
                width: 20,
                style: ListStyle.GREEN as Partial<Column>,
            },
        ],
    },
    {
        header: 'Tạo đề nghị thanh toán',
        key: 'commissionPayRequest',
        width: 30,
        style: ListStyle.GREEN as Partial<Column>,
    },
];

export const importDebtCompartionCustomizeHeader: ICustomizeCell[] = [
    {
        key: 'company_name',
        cell: 'A1',
        value: 'CÔNG TY TNHH SX TM THÉP ĐÔNG ANH',
        colSpan: 4,
        style: {
            font: { bold: true, size: 14 },
            alignment: { vertical: 'middle', horizontal: 'center' },
        },
    },
    {
        key: 'vn',
        cell: 'F1',
        value: 'CỘNG HOÀ XÃ HỘI CHỦ NGHĨA VIỆT NAM',
        colSpan: 4,
        style: {
            font: { bold: true, size: 14 },
            alignment: { vertical: 'middle', horizontal: 'center' },
        },
    },
    {
        key: 'tax',
        cell: 'A2',
        value: 'Số: 123456',
        colSpan: 4,
        style: {
            font: { bold: false, size: 14 },
            alignment: { vertical: 'middle', horizontal: 'center' },
        },
    },
    {
        key: 'vn',
        cell: 'F2',
        value: 'Độc lập_Tự do_Hạnh phúc',
        colSpan: 4,
        style: {
            font: { bold: false, size: 14 },
            alignment: { vertical: 'middle', horizontal: 'center' },
        },
    },
    {
        key: 'title',
        cell: 'A3',
        colSpan: 9,
        value: 'BIÊN BẢN ĐỐI CHIẾU CÔNG NỢ',
        dataValidation: {} as DataValidation,
        style: {
            font: { bold: true, size: 32 },
            alignment: { vertical: 'middle', horizontal: 'center' },
            fill: {
                type: 'pattern',
                pattern: 'solid',
                fgColor: { argb: 'FFFFFF' },
            },
        },
    },
    {
        key: 'note1',
        cell: 'B4',
        colSpan: 8,
        value: '- Căn cứ vào biên bản giao nhận hàng hoá',
        dataValidation: {} as DataValidation,
        style: {
            font: { bold: false, size: 12, italic: true },
            alignment: { vertical: 'middle', horizontal: 'left' },
        },
    },
    {
        key: 'note2',
        cell: 'B5',
        colSpan: 8,
        value: '- Căn cứ vào thỏa thuận giữa hai bên',
        dataValidation: {} as DataValidation,
        style: {
            font: { bold: false, size: 12, italic: true },
            alignment: { vertical: 'middle', horizontal: 'left' },
        },
    },
    {
        key: 'note3',
        cell: 'A6',
        colSpan: 9,
        value: 'Hôm này ngày...tháng...năm 2025 tại trụ sở thép Đông Anh chúng tôi gồm có',
        dataValidation: {} as DataValidation,
        style: {
            font: { bold: false, size: 12 },
            alignment: { vertical: 'middle', horizontal: 'left' },
        },
    },
    {
        key: 'buyer',
        cell: 'A7',
        colSpan: 2,
        value: 'I. Bên mua (Bên A) : ',
        dataValidation: {} as DataValidation,
        style: {
            font: { bold: true, size: 12 },
            alignment: { vertical: 'middle', horizontal: 'left' },
        },
    },
    {
        key: 'buyerValue',
        cell: 'D7',
        colSpan: 7,
        value: 'CÔNG TY TNHH SX TM THÉP ĐÔNG ANH',
        dataValidation: {} as DataValidation,
        style: {
            font: { bold: true, size: 12 },
            alignment: { vertical: 'middle', horizontal: 'left' },
        },
    },
    {
        key: 'address',
        cell: 'A8',
        colSpan: 4,
        value: 'Địa chỉ:',
        dataValidation: {} as DataValidation,
        style: {
            font: { bold: false, size: 12 },
            alignment: { vertical: 'middle', horizontal: 'left' },
        },
    },
    {
        key: 'phon',
        cell: 'F8',
        colSpan: 4,
        value: 'Điện thoại:',
        dataValidation: {} as DataValidation,
        style: {
            font: { bold: false, size: 12 },
            alignment: { vertical: 'middle', horizontal: 'left' },
        },
    },
    {
        key: 'represent',
        cell: 'A9',
        colSpan: 1,
        value: 'Đại diện:',
        dataValidation: {} as DataValidation,
        style: {
            font: { bold: false, size: 12 },
            alignment: { vertical: 'middle', horizontal: 'left' },
        },
    },
    {
        key: 'position',
        cell: 'F9',
        colSpan: 0,
        value: 'Chức vụ:',
        dataValidation: {} as DataValidation,
        style: {
            font: { bold: false, size: 12 },
            alignment: { vertical: 'middle', horizontal: 'left' },
        },
    },
    {
        key: 'positionValue',
        cell: 'G9',
        colSpan: 0,
        value: 'Giám đốc',
        dataValidation: {} as DataValidation,
        style: {
            font: { bold: false, size: 12 },
            alignment: { vertical: 'middle', horizontal: 'left' },
        },
    },
    {
        key: 'seller',
        cell: 'A10',
        colSpan: 0,
        value: 'II. Bên bán (Bên B) : ',
        dataValidation: {} as DataValidation,
        style: {
            font: { bold: true, size: 12 },
            alignment: { vertical: 'middle', horizontal: 'left' },
        },
    },
    {
        key: 'sellerValue',
        cell: 'D10',
        colSpan: 0,
        value: 'CÔNG TY CP Hoà Phát',
        dataValidation: {} as DataValidation,
        style: {
            font: { bold: true, size: 12 },
            alignment: { vertical: 'middle', horizontal: 'left' },
        },
    },
    {
        key: 'code',
        cell: 'H10',
        colSpan: 0,
        value: 'Mã KH',
        dataValidation: {} as DataValidation,
        style: {
            font: { bold: true, size: 12 },
            alignment: { vertical: 'middle', horizontal: 'left' },
        },
    },
    {
        key: 'address1',
        cell: 'A11',
        colSpan: 0,
        value: 'Địa chỉ:',
        dataValidation: {} as DataValidation,
        style: {
            font: { bold: false, size: 12 },
            alignment: { vertical: 'middle', horizontal: 'left' },
        },
    },
    {
        key: 'phon1',
        cell: 'F11',
        colSpan: 0,
        value: 'Điện thoại:',
        dataValidation: {} as DataValidation,
        style: {
            font: { bold: false, size: 12 },
            alignment: { vertical: 'middle', horizontal: 'left' },
        },
    },
    {
        key: 'represent1',
        cell: 'A12',
        colSpan: 0,
        value: 'Đại diện:',
        dataValidation: {} as DataValidation,
        style: {
            font: { bold: false, size: 12 },
            alignment: { vertical: 'middle', horizontal: 'left' },
        },
    },
    {
        key: 'position1',
        cell: 'F12',
        colSpan: 0,
        value: 'Chức vụ:',
        dataValidation: {} as DataValidation,
        style: {
            font: { bold: false, size: 12 },
            alignment: { vertical: 'middle', horizontal: 'left' },
        },
    },
    {
        key: 'positionValue1',
        cell: 'G12',
        colSpan: 0,
        value: 'Giám đốc',
        dataValidation: {} as DataValidation,
        style: {
            font: { bold: false, size: 12 },
            alignment: { vertical: 'middle', horizontal: 'left' },
        },
    },
    {
        key: 'note4',
        cell: 'B13',
        colSpan: 0,
        value: 'Cùng nhau đối chiếu công nợ giữa hai bên với số liệu như sau:',
        dataValidation: {} as DataValidation,
        style: {
            font: { bold: false, size: 12 },
            alignment: { vertical: 'middle', horizontal: 'left' },
        },
    },
    {
        key: 'index',
        cell: 'A14',
        colSpan: 0,
        value: '1',
        dataValidation: {} as DataValidation,
        style: {
            font: { bold: false, size: 12 },
            alignment: { vertical: 'middle', horizontal: 'center' },
        },
    },
    {
        key: 'index1',
        cell: 'A15',
        colSpan: 0,
        value: '2',
        dataValidation: {} as DataValidation,
        style: {
            font: { bold: false, size: 12 },
            alignment: { vertical: 'middle', horizontal: 'center' },
        },
    },
    {
        key: 'index2',
        cell: 'B14',
        colSpan: 0,
        value: 'Công nợ đầu kỳ:',
        dataValidation: {} as DataValidation,
        style: {
            font: { bold: false, size: 12 },
            alignment: { vertical: 'middle', horizontal: 'left' },
        },
    },
    {
        key: 'index3',
        cell: 'N14',
        colSpan: 0,
        value: 'Công nợ đầu kỳ:',
        dataValidation: {} as DataValidation,
        style: {
            font: { bold: false, size: 12 },
            alignment: { vertical: 'middle', horizontal: 'left' },
        },
    },
    {
        key: 'index4',
        cell: 'B15',
        colSpan: 0,
        value: 'Công nợ phát sinh trong kỳ:',
        dataValidation: {} as DataValidation,
        style: {
            font: { bold: false, size: 12 },
            alignment: { vertical: 'middle', horizontal: 'left' },
        },
    },
];

export const importDebtCompartionCustomizeFooter: ICustomizeCell[] = [
    // {
    //     key: 'f_sum1',
    //     cell: 'A20',
    //     colSpan: 3,
    //     value: 'Tổng',
    //     dataValidation: {} as DataValidation,
    //     style: {
    //         font: { bold: true, size: 14 },
    //         alignment: { vertical: 'middle', horizontal: 'center' },
    //         border: {
    //             top: { style: 'thin' },
    //             left: { style: 'thin' },
    //             bottom: { style: 'thin' },
    //             right: { style: 'thin' },
    //         },
    //     },
    // },
    // {
    //     key: 'f_sum2',
    //     cell: 'M28',
    //     colSpan: 0,
    //     value: 'Tổng',
    //     dataValidation: {} as DataValidation,
    //     style: {
    //         font: { bold: true, size: 14 },
    //         alignment: { vertical: 'middle', horizontal: 'center' },
    //         border: {
    //             top: { style: 'thin' },
    //             left: { style: 'thin' },
    //             bottom: { style: 'thin' },
    //             right: { style: 'thin' },
    //         },
    //     },
    // },
    // {
    //     key: 'f_intoMoney',
    //     cell: 'E28',
    //     colSpan: 0,
    //     value: { formula: 'SUM(E19:E27)' },
    //     dataValidation: {} as DataValidation,
    //     style: {
    //         font: { bold: true, size: 14 },
    //         alignment: { vertical: 'middle', horizontal: 'center' },
    //         border: {
    //             top: { style: 'thin' },
    //             left: { style: 'thin' },
    //             bottom: { style: 'thin' },
    //             right: { style: 'thin' },
    //         },
    //     },
    // },
    // {
    //     key: 'f_money',
    //     cell: 'F28',
    //     colSpan: 0,
    //     value: { formula: 'SUM(F19:F27)' },
    //     dataValidation: {} as DataValidation,
    //     style: {
    //         font: { bold: true, size: 14 },
    //         alignment: { vertical: 'middle', horizontal: 'center' },
    //         border: {
    //             top: { style: 'thin' },
    //             left: { style: 'thin' },
    //             bottom: { style: 'thin' },
    //             right: { style: 'thin' },
    //         },
    //     },
    // },
    // {
    //     key: 'f_debt',
    //     cell: 'I28',
    //     colSpan: 0,
    //     value: { formula: 'SUM(I19:I27) + D14' },
    //     dataValidation: {} as DataValidation,
    //     style: {
    //         font: { bold: true, size: 14 },
    //         alignment: { vertical: 'middle', horizontal: 'center' },
    //         border: {
    //             top: { style: 'thin' },
    //             left: { style: 'thin' },
    //             bottom: { style: 'thin' },
    //             right: { style: 'thin' },
    //         },
    //     },
    // },
    // {
    //     key: 'f_payRequest',
    //     cell: 'L28',
    //     colSpan: 0,
    //     value: { formula: 'SUM(L19:L27) + O14' },
    //     dataValidation: {} as DataValidation,
    //     style: {
    //         font: { bold: true, size: 14 },
    //         alignment: { vertical: 'middle', horizontal: 'center' },
    //         border: {
    //             top: { style: 'thin' },
    //             left: { style: 'thin' },
    //             bottom: { style: 'thin' },
    //             right: { style: 'thin' },
    //         },
    //     },
    // },
    // {
    //     key: 'f_cn',
    //     cell: 'N28',
    //     colSpan: 0,
    //     value: { formula: 'SUM(N19:N27)' },
    //     dataValidation: {} as DataValidation,
    //     style: {
    //         font: { bold: true, size: 14 },
    //         alignment: { vertical: 'middle', horizontal: 'center' },
    //         border: {
    //             top: { style: 'thin' },
    //             left: { style: 'thin' },
    //             bottom: { style: 'thin' },
    //             right: { style: 'thin' },
    //         },
    //     },
    // },
    //     {
    //     key: 'f_payment',
    //     cell: 'O28',
    //     colSpan: 0,
    //     value: { formula: 'SUM(O19:O27)' },
    //     dataValidation: {} as DataValidation,
    //     style: {
    //         font: { bold: true, size: 14 },
    //         alignment: { vertical: 'middle', horizontal: 'center' },
    //         border: {
    //             top: { style: 'thin' },
    //             left: { style: 'thin' },
    //             bottom: { style: 'thin' },
    //             right: { style: 'thin' },
    //         },
    //     },
    // },
];

export const dataFakeDebtCompartion = [
    {
        id: 1,
        date: '20/02/2022',
        vat: '10',
        content: 'hahaha',
        intoMoney: 200000,
        money: 10000,
        paymentDate: '10/04/2025',
        bank: 'MB BANK',
        debt: 10000,
        orderNumber: 'ĐH101',
        paymentTerm: '12/12/2025',
        payRequest: 'OK',
        commission: '5%',
        commissionMoney: 20000,
        commissionPay: 2000,
        commissionDate: '10/03/2025',
        commissionBank: 'BIDV',
        commissionDebt: 3000,
        phone: '0989746253',
        name: 'HEHE',
        commissionPayRequest: 'OKELA',
    },
    {
        id: 2,
        date: '20/02/2022',
        vat: '10',
        content: 'hahaha',
        intoMoney: 200000,
        money: 10000,
        paymentDate: '10/04/2025',
        bank: 'MB BANK',
        debt: 10000,
        orderNumber: 'ĐH101',
        paymentTerm: '12/12/2025',
        payRequest: 'OK',
        commission: '5%',
        commissionMoney: 20000,
        commissionPay: 2000,
        commissionDate: '10/03/2025',
        commissionBank: 'BIDV',
        commissionDebt: 3000,
        phone: '0989746253',
        name: 'HEHE',
        commissionPayRequest: 'OKELA',
    },
];
