services:
  postgresql:
    container_name: postgresql
    image: postgres:latest
    volumes:
      - postgresql_data:/var/lib/postgresql/data
      - postgresql_log:/var/log/postgresql
    environment:
      - POSTGRES_USER=${DB_USER_NAME}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_DB=${DB_NAME}
    ports:
      - "5432:5432"
    networks:
      - backend_network
    restart: always    

  redis:
    container_name: redis
    image: redis:latest
    volumes:
      - redis_data:/data
    ports:
      - "6379:6379"
    networks:
      - backend_network
    restart: always

  backend_service:
    image: backend_service
    build:
      context: .
      dockerfile: ./Dockerfile
    depends_on:
      - postgresql
      - redis
    environment:
      - DATABASE_URL=${DATABASE_URL}
      - REDIS_URI=${REDIS_URI}
      - LOG_LEVEL=${LOG_LEVEL}
    env_file:
      - .env
    networks:
      - backend_network
    ports:
      - "4000:4000"
    restart: always

networks:
  backend_network:
    driver: bridge

volumes:
  postgresql_data:
    driver: local
  postgresql_log:
    driver: local
  redis_data:
    driver: local
