FROM node:23.11.0-slim as base
# FROM node:22.12.0 as base

WORKDIR /app

COPY package*.json ./

RUN yarn install

COPY . .

RUN npx prisma generate

RUN yarn build


FROM base as be_thep_dong_anh

WORKDIR /app

EXPOSE 4200

CMD [ "npm", "start" ]