import express from 'express';
import authRoutes from '@api/routes/auth.route';
import otherRoutes from '@api/routes/other.route';
import employeeRoutes from '@api/routes/employee.route';
import userRoutes from '@api/routes/user.route';
import roleRoutes from '@api/routes/role.route';
import deviceRequestRoutes from '@api/routes/device-request.route';
import partnerRoutes from '@api/routes/partner.route';
import partnerGroupRoutes from '@api/routes/partner-group.route';
import organizationRoutes from '@api/routes/organization.route';
import positionRoutes from '@api/routes/position.route';
import jobPositionRoutes from '@api/routes/job-position.route';
import bankRoutes from '@api/routes/bank.route';
import clauseRoutes from '@api/routes/clause.route';
import warehouseRoutes from '@api/routes/warehouse.route';
import unitRoutes from '@api/routes/unit.route';
import productRoutes from '@api/routes/product.route';
import quotationRoutes from '@api/routes/quotation.route';
import quotationRequestRoutes from '@api/routes/quotation-request.route';
import purchaseRequestRoutes from '@api/routes/purchase-request.route';
import productGroupRoutes from '@api/routes/product-group.route';
import contractRoutes from '@api/routes/contract.route';
import invoiceRoutes from '@api/routes/invoice.route';
import productionRoutes from '@api/routes/production.route';
import orderRoutes from '@api/routes/order.route';
import billOfMaterialRoutes from '@api/routes/bill-of-material.route';
import orderExpenseRoutes from '@api/routes/order-expense.route';
import inventoryRoutes from '@api/routes/inventory.route';
import paymentRequestRoutes from '@api/routes/payment-request.route';
import representativeRoutes from '@api/routes/representative.route';
import paymentRoutes from '@api/routes/payment.route';
import excelRouter from '@api/routes/excel.route';
import transactionRouter from '@api/routes/transaction.route';
import publicRoutes from '@api/routes/public.route';
import shippingPlanRoutes from '@api/routes/shipping-plan.route';
import { AuthMiddleware } from './middlewares/auth.middleware';
import { UserDeviceMiddleware } from './middlewares/user-device.middleware';
import { SpatialClassificationMiddleware } from './middlewares/spatial-classification.middleware';

const router = express.Router();

router.use(UserDeviceMiddleware.getUserDevice);
router.use('/auth', authRoutes);
router.use(SpatialClassificationMiddleware.handle);
router.use('/', publicRoutes);
router.use(AuthMiddleware.authenticate);
router.use('/', otherRoutes);
router.use('/employee', employeeRoutes);
router.use('/user', userRoutes);
router.use('/bank', bankRoutes);
router.use('/device-request', deviceRequestRoutes);
router.use('/role', roleRoutes);
router.use('/partner', partnerRoutes);
router.use('/partner-group', partnerGroupRoutes);
router.use('/organization', organizationRoutes);
router.use('/position', positionRoutes);
router.use('/job-position', jobPositionRoutes);
router.use('/clause', clauseRoutes);
router.use('/warehouse', warehouseRoutes);
router.use('/quotation-request', quotationRequestRoutes);
router.use('/purchase-request', purchaseRequestRoutes);
router.use('/product', productRoutes);
router.use('/product-group', productGroupRoutes);
router.use('/unit', unitRoutes);
router.use('/quotation', quotationRoutes);
router.use('/contract', contractRoutes);
router.use('/invoice', invoiceRoutes);
router.use('/production', productionRoutes);
router.use('/order', orderRoutes);
router.use('/bill-of-material', billOfMaterialRoutes);
router.use('/order-expense', orderExpenseRoutes);
router.use('/inventory', inventoryRoutes);
router.use('/payment-request', paymentRequestRoutes);
router.use('/representative', representativeRoutes);
router.use('/excel', excelRouter);
router.use('/payment', paymentRoutes);
router.use('/shipping-plan', shippingPlanRoutes);
router.use('/transaction', transactionRouter);

export default router;
