name: deploy-prd-v1

on:
    push:
        branches: ['main']

jobs:
    deploy:
        name: Deploy App
        runs-on: ubuntu-22.04

        steps:
            - name: Checkout code
              uses: actions/checkout@v3

            - name: Setup Node.js
              uses: actions/setup-node@v3
              with:
                  node-version: 22.12.0

            - name: Install dependencies
              run: yarn

            - name: Build project
              run: yarn build

            - name: Archive build
              run: |
                  tar -czf dist.tar.gz dist package.json yarn.lock

            - name: Copy files to VPS
              uses: appleboy/scp-action@v0.1.7
              with:
                  host: ${{ secrets.HOST }}
                  username: ${{ secrets.USERNAME }}
                  key: ${{ secrets.PRIVATE_KEY }}
                  source: 'dist.tar.gz'
                  target: '~/erp/DA_BE'

            - name: Deploy on VPS
              uses: appleboy/ssh-action@v1.0.0
              with:
                  host: ${{ secrets.HOST }}
                  username: ${{ secrets.USERNAME }}
                  key: ${{ secrets.PRIVATE_KEY }}
                  script: |
                      cd ~/erp/DA_BE
                      tar -xzf dist.tar.gz
                      rm dist.tar.gz
                      yarn install
                      yarn prisma:push
                      yarn pm2:reload
